/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
      ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
      ElForm: typeof import('element-plus/es')['ElForm']
      ElFormItem: typeof import('element-plus/es')['ElFormItem']
      ElIcon: typeof import('element-plus/es')['ElIcon']
      ElInput: typeof import('element-plus/es')['ElInput']
      ElMenu: typeof import('element-plus/es')['ElMenu']
      ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
      ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
      ElSelect: typeof import('element-plus/es')['ElSelect']
    HostBottom: typeof import('./src/components/HostBottom/hostBottom.vue')['default']
    HostTop: typeof import('./src/components/HostTop/hostTop.vue')['default']
      Login: typeof import('./src/components/login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
